name: Python CI
on:
    push:
         branches:
                  - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout Repository
         uses: actions/checkout@v4 #Downloads your GitHub repository

       - name: Set up Python
         uses: actions/setup-python@v5
         with:
          python-version: "3.14"

       - name: Install dependencies
         run: pip install -r requirements.txt
        
        #similar to docker login 
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        #Build the image Instead of: docker build -t pak-news-summarizer 
       - name: Build Docker image
         run: docker build -t meerubsk/pak-news-summarizer:latest .

        #Push the image
       - name: Push Docker image
         run: docker push meerubsk/pak-news-summarizer:latest